// Generated by Stack-Figma/icons/make_icons.py from the same drawings as the
// Figma board. Edit the drawings there and re-run it; don't edit this file.
import type { SVGProps } from "react";

type P = SVGProps<SVGSVGElement> & { size?: number };

const glyph = ({ size = 24, ...p }: P, filled = false) => ({
  width: size,
  height: size,
  viewBox: "0 0 24 24",
  fill: filled ? "currentColor" : "none",
  stroke: "currentColor",
  strokeWidth: 1.7,
  strokeLinejoin: "round" as const,
  strokeLinecap: "round" as const,
  "aria-hidden": true,
  ...p,
});

// ---- Actions ----
export const EditIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 20h4L19 9l-4-4L4 16z"/><path d="M13 7l4 4"/></svg>
);
export const CopyIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h3"/></svg>
);
export const UndoIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M9 14L4 9l5-5"/><path d="M4 9h10.5a5.5 5.5 0 0 1 0 11H11"/></svg>
);
export const RedoIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M15 14l5-5-5-5"/><path d="M20 9H9.5a5.5 5.5 0 0 0 0 11H13"/></svg>
);
export const LinkIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M10 14a4.5 4.5 0 0 0 6.4 0l3-3a4.5 4.5 0 0 0-6.4-6.4l-1 1"/><path d="M14 10a4.5 4.5 0 0 0-6.4 0l-3 3a4.5 4.5 0 0 0 6.4 6.4l1-1"/></svg>
);
export const DownloadIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 4v11M7.5 10.5 12 15l4.5-4.5"/><path d="M5 19h14"/></svg>
);
export const UploadIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 16V4M7.5 8.5 12 4l4.5 4.5"/><path d="M5 19h14"/></svg>
);
export const PlusCircleIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="9"/><path d="M12 8v8M8 12h8"/></svg>
);
export const CheckCircleIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="9"/><path d="M8 12.5l2.7 2.7L16 10"/></svg>
);
export const CheckboxIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="4" y="4" width="16" height="16" rx="3"/></svg>
);
export const CheckboxCheckedIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="4" y="4" width="16" height="16" rx="3"/><path d="M8 12l3 3 5-6"/></svg>
);
export const ArchiveIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="3" y="4" width="18" height="4" rx="1"/><path d="M5 8v11a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8"/><path d="M10 12h4"/></svg>
);
export const SortIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M7 4v16M3.5 16.5 7 20l3.5-3.5"/><path d="M17 20V4M13.5 7.5 17 4l3.5 3.5"/></svg>
);
export const FilterIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 5h16l-6 7.5V19l-4 1.5v-8z"/></svg>
);
export const ExpandIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M14 4h6v6M10 20H4v-6M20 4l-7 7M4 20l7-7"/></svg>
);
export const EyeIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M2.5 12S6 5 12 5s9.5 7 9.5 7-3.5 7-9.5 7S2.5 12 2.5 12z"/><circle cx="12" cy="12" r="3"/></svg>
);
export const MoreIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M5 12h.01"/><path d="M12 12h.01"/><path d="M19 12h.01"/></svg>
);
export const MoreVerticalIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 5h.01"/><path d="M12 12h.01"/><path d="M12 19h.01"/></svg>
);
export const DragIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M9 6h.01"/><path d="M15 6h.01"/><path d="M9 12h.01"/><path d="M15 12h.01"/><path d="M9 18h.01"/><path d="M15 18h.01"/></svg>
);

// ---- Views & layout ----
export const CardsIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="8" y="3" width="12" height="15" rx="2"/><path d="M5 6.5V19a2 2 0 0 0 2 2h9"/></svg>
);
export const ListViewIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M8.5 6h11.5M8.5 12h11.5M8.5 18h11.5"/><path d="M4 6h.01"/><path d="M4 12h.01"/><path d="M4 18h.01"/></svg>
);
export const GridIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="4" y="4" width="7" height="7" rx="1"/><rect x="13" y="4" width="7" height="7" rx="1"/><rect x="4" y="13" width="7" height="7" rx="1"/><rect x="13" y="13" width="7" height="7" rx="1"/></svg>
);
export const RailIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M8 4v16"/><path d="M5.5 8h.01"/><path d="M5.5 12h.01"/><path d="M5.5 16h.01"/></svg>
);
export const InboxIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M3 13l2.5-8h13L21 13v6a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/><path d="M3 13h5l1.5 2.5h5L16 13h5"/></svg>
);
export const CalendarIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="3" y="4.5" width="18" height="16" rx="2"/><path d="M3 9.5h18M8 2.5v4M16 2.5v4"/></svg>
);

// ---- Reading & library ----
export const ReadingIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 6.5c-2-1.5-5-2-8-1.5v14c3-.5 6 0 8 1.5 2-1.5 5-2 8-1.5V5c-3-.5-6 0-8 1.5z"/><path d="M12 6.5V20.5"/></svg>
);
export const ReaderModeIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>
);
export const HighlighterIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M14.5 4l5.5 5.5-8.5 8.5-5.5-5.5z"/><path d="M6 12.5l-2.5 5.5 2.5 2.5 5.5-2.5"/><path d="M3 21h5"/></svg>
);
export const NoteAddIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M6 3h9l4 4v14H6z"/><path d="M12.5 10.5v6M9.5 13.5h6"/></svg>
);
export const QuoteIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M10 7H5v5h5v1c0 2.5-1.5 4-4 5"/><path d="M19 7h-5v5h5v1c0 2.5-1.5 4-4 5"/></svg>
);
export const FilePdfIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M6 3h9l4 4v14H6z"/><path d="M15 3v4h4"/><path d="M9 17v-4h1.5a1.5 1.5 0 0 1 0 3H9M14 13v4"/></svg>
);
export const FolderIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M3 6a1 1 0 0 1 1-1h5l2 2.5h9a1 1 0 0 1 1 1V19a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/></svg>
);
export const PhoneImportIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="6" y="2.5" width="12" height="19" rx="2.5"/><path d="M12 6.5v7M9 10.5l3 3 3-3"/><path d="M10.5 18.5h3"/></svg>
);
export const ZoomInIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="11" cy="11" r="6.5"/><path d="M16 16l5 5"/><path d="M11 8v6M8 11h6"/></svg>
);
export const ZoomOutIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="11" cy="11" r="6.5"/><path d="M16 16l5 5"/><path d="M8 11h6"/></svg>
);
export const TextSizeIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M3 18l5-12 5 12M4.8 14h6.4"/><path d="M14.5 18l3-7 3 7M15.5 16h4"/></svg>
);
export const HistoryIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M3.5 12a8.5 8.5 0 1 0 2.5-6"/><path d="M3.5 4.5v4h4"/><path d="M12 8v4l3 2"/></svg>
);
export const NewspaperIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 5h13v13a2 2 0 0 0 2 2H6a2 2 0 0 1-2-2z"/><path d="M17 9h3v9a2 2 0 0 1-2 2"/><path d="M7.5 9h6M7.5 12.5h6M7.5 16h3.5"/></svg>
);
export const ImageIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9.5" r="1.5"/><path d="M21 16l-5-5-9 9"/></svg>
);

// ---- News topics ----
export const TrendingIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M3 17l6-6 4 4 8-8"/><path d="M15 7h6v6"/></svg>
);
export const ContrastIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="9"/><path d="M12 3a9 9 0 0 1 0 18z" fill="currentColor"/></svg>
);
export const FlagIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M5 21V4"/><path d="M5 4h13l-2.5 4.5L18 13H5"/></svg>
);
export const GlobeIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="9"/><path d="M3 12h18"/><path d="M12 3c2.5 2.5 3.8 5.5 3.8 9s-1.3 6.5-3.8 9c-2.5-2.5-3.8-5.5-3.8-9S9.5 5.5 12 3z"/></svg>
);
export const ChipIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="6" y="6" width="12" height="12" rx="2"/><rect x="9.5" y="9.5" width="5" height="5" rx="0.5"/><path d="M9 3v3M15 3v3M9 18v3M15 18v3M3 9h3M3 15h3M18 9h3M18 15h3"/></svg>
);
export const SparkleIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M11 3l1.8 5.2L18 10l-5.2 1.8L11 17l-1.8-5.2L4 10l5.2-1.8z"/><path d="M18.5 15l.7 1.8 1.8.7-1.8.7-.7 1.8-.7-1.8-1.8-.7 1.8-.7z"/></svg>
);
export const CodeIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M8 7l-5 5 5 5M16 7l5 5-5 5M14 4l-4 16"/></svg>
);
export const BriefcaseIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 7V5a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/><path d="M3 12.5h18"/></svg>
);
export const FlaskIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M9.5 3h5M10 3v6l-5.5 9.5A1.7 1.7 0 0 0 6 21h12a1.7 1.7 0 0 0 1.5-2.5L14 9V3"/><path d="M7 15h10"/></svg>
);
export const BallIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="9"/><path d="M12 7.5l4.2 3-1.6 5H9.4l-1.6-5z"/><path d="M12 3v4.5M16.2 10.5l4.3-1.4M14.6 15.5l2.7 3.8M9.4 15.5l-2.7 3.8M7.8 10.5 3.5 9.1"/></svg>
);
export const ClapperIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 10h16v9a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z"/><path d="M4 10l-.6-3.2a1 1 0 0 1 .8-1.2l13.8-2.5a1 1 0 0 1 1.2.8L19.6 7z"/><path d="M8 5.6l2.2 3.2M13 4.7l2.2 3.2"/></svg>
);
export const HealthIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 20s-8-4.7-8-10.5A4.5 4.5 0 0 1 12 7a4.5 4.5 0 0 1 8 2.5C20 15.3 12 20 12 20z"/><path d="M7 12.5h2.5l1.2-2 2 4 1.3-2H17"/></svg>
);
export const RssIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M5 19h.01"/><path d="M5 12a7 7 0 0 1 7 7"/><path d="M5 5a14 14 0 0 1 14 14"/></svg>
);

// ---- Music ----
export const MusicNoteIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M9 18V5l11-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="17" cy="16" r="3"/></svg>
);
export const PlaylistIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M3 6h12M3 11h12M3 16h7"/><circle cx="17.5" cy="17.5" r="2.5"/><path d="M20 17.5V8l2-.5"/></svg>
);
export const HeartIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 20s-8-4.7-8-10.5A4.5 4.5 0 0 1 12 7a4.5 4.5 0 0 1 8 2.5C20 15.3 12 20 12 20z"/></svg>
);
export const HeartFilledIcon = (p: P) => (
  <svg {...glyph(p, true)}><path d="M12 20s-8-4.7-8-10.5A4.5 4.5 0 0 1 12 7a4.5 4.5 0 0 1 8 2.5C20 15.3 12 20 12 20z"/></svg>
);
export const AlbumIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="12" cy="12" r="5"/><path d="M12 12h.01"/></svg>
);
export const QueueIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M3 6h13M3 11h13M3 16h8"/><path d="M15 14v6l5-3z"/></svg>
);
export const VolumeIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 9.5h3.5L12 5.5v13l-4.5-4H4z"/><path d="M16 9a4 4 0 0 1 0 6M18.5 6.5a7.5 7.5 0 0 1 0 11"/></svg>
);
export const VolumeOffIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 9.5h3.5L12 5.5v13l-4.5-4H4z"/><path d="M16 9.5l5 5M21 9.5l-5 5"/></svg>
);
export const PhoneMusicIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="6" y="2.5" width="12" height="19" rx="2.5"/><path d="M13.5 14V8l2 .7"/><circle cx="12" cy="14" r="1.5"/><path d="M10.5 18.5h3"/></svg>
);
export const HeadphonesIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 17v-4a8 8 0 0 1 16 0v4"/><path d="M4 14.5h3v6H5a1 1 0 0 1-1-1zM20 14.5h-3v6h2a1 1 0 0 0 1-1z"/></svg>
);
export const MixerIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M6 4v16M12 4v16M18 4v16"/><path d="M4 14h4M10 8h4M16 16h4"/></svg>
);
export const MicIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="9" y="3" width="6" height="11" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3"/></svg>
);

// ---- Focus & review ----
export const TimerIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="13.5" r="7.5"/><path d="M12 10v3.5l2.5 1.5"/><path d="M9.5 2.5h5"/><path d="M19 6l1.5-1.5"/></svg>
);
export const TargetIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="M12 12h.01"/></svg>
);
export const GoalIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 3.5a8.5 8.5 0 1 1-7.9 5.3"/><path d="M8.5 12l2.5 2.5 4.5-4.5"/></svg>
);
export const FocusModeIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 8V5a1 1 0 0 1 1-1h3M16 4h3a1 1 0 0 1 1 1v3M20 16v3a1 1 0 0 1-1 1h-3M8 20H5a1 1 0 0 1-1-1v-3"/><circle cx="12" cy="12" r="3"/></svg>
);
export const StopIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="6" y="6" width="12" height="12" rx="2"/></svg>
);
export const ReviewIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 12a8 8 0 0 1 13.7-5.6"/><path d="M18 3v4h-4"/><path d="M20 12a8 8 0 0 1-13.7 5.6"/><path d="M6 21v-4h4"/><path d="M12 12h.01"/></svg>
);
export const AgainIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 12a8 8 0 1 0 2.3-5.7"/><path d="M4 4v4.5h4.5"/></svg>
);
export const BrainIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M9 4.5A2.5 2.5 0 0 0 6.5 7v.2A3 3 0 0 0 4.5 12 3 3 0 0 0 6 17a3 3 0 0 0 6 0V7a2.5 2.5 0 0 0-3-2.5z"/><path d="M15 4.5A2.5 2.5 0 0 1 17.5 7v.2a3 3 0 0 1 2 4.8 3 3 0 0 1-1.5 5 3 3 0 0 1-6 0"/></svg>
);

// ---- Profile, progress & badges ----
export const UserIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="8" r="4"/><path d="M4 21c0-4.4 3.6-7 8-7s8 2.6 8 7"/></svg>
);
export const CameraIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 8h3l2-3h6l2 3h3v11H4z"/><circle cx="12" cy="13" r="3.5"/></svg>
);
export const ProfileCardIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="9" cy="11" r="2.5"/><path d="M5.5 17c.6-2 1.9-3 3.5-3s2.9 1 3.5 3M15 10h3M15 13.5h3"/></svg>
);
export const StreakIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 3c.8 3.2 5.5 5 5.5 10.5a5.5 5.5 0 0 1-11 0c0-2.3 1-3.9 2.2-5 .1 2 1 3.3 2.3 3.3C11 9 10.3 6.3 12 3z"/></svg>
);
export const BadgeIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="9" r="6"/><path d="M8.6 13.9 7 21l5-2.8 5 2.8-1.6-7.1"/><path d="M12 6.5l.8 1.6 1.7.2-1.2 1.2.3 1.7-1.6-.8-1.6.8.3-1.7-1.2-1.2 1.7-.2z"/></svg>
);
export const MedalIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M8 3l4 7 4-7"/><circle cx="12" cy="15" r="6"/><path d="M12 12.5v5M10.5 13.5 12 12.5"/></svg>
);
export const TrophyIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M7 4h10v5a5 5 0 0 1-10 0z"/><path d="M7 6H4v1a3 3 0 0 0 3 3M17 6h3v1a3 3 0 0 1-3 3"/><path d="M12 14v4M8 21h8M9 18h6"/></svg>
);
export const ChartIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 20h16"/><path d="M7 16v-5M12 16V6M17 16V9"/></svg>
);
export const HeatmapIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="3" y="4" width="18" height="17" rx="2"/><path d="M3 9h18M8 2v4M16 2v4"/><path d="M8 13h.01"/><path d="M12 13h.01"/><path d="M16 13h.01"/><path d="M8 17h.01"/><path d="M12 17h.01"/></svg>
);
export const StarIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 3l2.7 5.6 6.1.8-4.5 4.2 1.1 6.1L12 16.8l-5.4 2.9 1.1-6.1-4.5-4.2 6.1-.8z"/></svg>
);
export const IdeaIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M9 18h6M10 21h4"/><path d="M12 3a6 6 0 0 0-3.6 10.8c.7.5 1.1 1.3 1.1 2.1V16h5v-.1c0-.8.4-1.6 1.1-2.1A6 6 0 0 0 12 3z"/></svg>
);
export const SproutIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 21v-8"/><path d="M12 13c0-4-3-6-7-6 0 4 3 6 7 6z"/><path d="M12 11c0-3.5 2.5-5.5 6.5-5.5 0 3.5-2.5 5.5-6.5 5.5z"/></svg>
);

// ---- Status & moods ----
export const InTheZoneIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 17v-4a8 8 0 0 1 16 0v4"/><path d="M4 14.5h3v6H5a1 1 0 0 1-1-1zM20 14.5h-3v6h2a1 1 0 0 0 1-1z"/><path d="M12 9v4"/></svg>
);
export const LearningIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M2 9.5l10-5 10 5-10 5z"/><path d="M6 11.5v4.5c2.5 2.3 9.5 2.3 12 0v-4.5"/><path d="M22 9.5V15"/></svg>
);
export const WritingIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 20l1-5L15.5 4.5l4 4L9 19z"/><path d="M13.5 6.5l4 4"/><path d="M13 20h7"/></svg>
);
export const BuildingIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M14 4l6 6-2 2-6-6z"/><path d="M13 9L4 18l2 2 9-9"/></svg>
);
export const BreakIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 9h13v5a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5z"/><path d="M17 11h1.5a2.5 2.5 0 0 1 0 5H17"/><path d="M8 3v3M12 3v3"/></svg>
);
export const NightOwlIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M20 14.5A8 8 0 1 1 9.5 4a6.5 6.5 0 0 0 10.5 10.5z"/></svg>
);
export const EarlyBirdIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.3-1.3M17.7 6.3l1.4-1.4"/></svg>
);
export const OfflineIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M5 12.5a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0"/><path d="M12 19.5h.01"/><path d="M3 3l18 18"/></svg>
);
export const RocketIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M14.5 4.5c2-1 4.5-1.5 5-1s0 3-1 5l-7 7-4-4z"/><path d="M8.5 11.5l-4-.5 3-3h4M12.5 15.5l.5 4 3-3v-4"/><path d="M5 19c0-1.5.5-2.5 2-3"/></svg>
);
export const GamepadIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M7 8h10a4 4 0 0 1 4 4v3a2.5 2.5 0 0 1-4.6 1.4L15 14.5H9l-1.4 1.9A2.5 2.5 0 0 1 3 15v-3a4 4 0 0 1 4-4z"/><path d="M7.5 11v3M6 12.5h3"/><path d="M15.5 11.5h.01"/><path d="M17 13.5h.01"/></svg>
);
export const DumbbellIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M6.5 6.5v11M17.5 6.5v11M3.5 9v6M20.5 9v6M6.5 12h11"/></svg>
);
export const TravelIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M21 3L3 10.5l7 2.5 2.5 7z"/><path d="M10 13l5-5"/></svg>
);
export const SickIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M10 14.5V5a2 2 0 0 1 4 0v9.5a4 4 0 1 1-4 0z"/><path d="M12 9v7"/></svg>
);
export const PartyIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 20l4.5-12 7.5 7.5z"/><path d="M13.5 7.5c1-1 1.5-2.5 1-4M16.5 10.5c1-1 2.5-1.5 4-1"/><path d="M19 5h.01"/><path d="M15 3.5h.01"/><path d="M20.5 13h.01"/></svg>
);
export const SmileIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="9"/><path d="M8.5 14.5c1 1.2 2.1 1.8 3.5 1.8s2.5-.6 3.5-1.8"/><path d="M9 10h.01"/><path d="M15 10h.01"/></svg>
);
export const ChatIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 5h16v11H9l-5 4z"/></svg>
);

// ---- Account & sync ----
export const MailIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/></svg>
);
export const KeyIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="8" cy="15" r="4"/><path d="M11 12l8.5-8.5M16 7l2.5 2.5M14 9l2 2"/></svg>
);
export const SignInIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M14 4h5v16h-5"/><path d="M9 8l4 4-4 4"/><path d="M13 12H3"/></svg>
);
export const SignOutIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M10 4H5v16h5"/><path d="M15 8l4 4-4 4"/><path d="M19 12H9"/></svg>
);
export const SyncIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M20 8A8.5 8.5 0 0 0 4.6 7.5"/><path d="M4 3.5v4h4"/><path d="M4 16a8.5 8.5 0 0 0 15.4.5"/><path d="M20 20.5v-4h-4"/></svg>
);
export const CloudDoneIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M7 18.5a4.5 4.5 0 0 1-.6-9A6 6 0 0 1 18 10a4.2 4.2 0 0 1-.5 8.5z"/><path d="M9.5 14l2 2 3.5-3.5"/></svg>
);
export const CloudOffIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M7 18.5a4.5 4.5 0 0 1-.6-9A6 6 0 0 1 18 10a4.2 4.2 0 0 1-.5 8.5z"/><path d="M3 3l18 18"/></svg>
);
export const DevicesIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="2" y="5" width="13" height="10" rx="1.5"/><path d="M5 19h7"/><rect x="17" y="8" width="5" height="12" rx="1.5"/></svg>
);
export const LockIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="5" y="10.5" width="14" height="10" rx="2"/><path d="M8 10.5V7.5a4 4 0 0 1 8 0v3"/><path d="M12 15.5h.01"/></svg>
);
export const ShieldIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 3l8 3v6c0 4.5-3.5 8-8 9-4.5-1-8-4.5-8-9V6z"/><path d="M9 12l2 2 4-4"/></svg>
);

// ---- Settings & system ----
export const SettingsIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M4 7h10M18 7h2M4 17h4M12 17h8"/><circle cx="16" cy="7" r="2"/><circle cx="10" cy="17" r="2"/></svg>
);
export const ThemeIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="8.5"/><path d="M12 3.5v17a8.5 8.5 0 0 0 0-17z"/></svg>
);
export const BellIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M6 16v-5a6 6 0 0 1 12 0v5l1.5 2h-15z"/><path d="M10 20.5a2 2 0 0 0 4 0"/></svg>
);
export const BellOffIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M6 16v-5a6 6 0 0 1 12 0v5l1.5 2h-15z"/><path d="M10 20.5a2 2 0 0 0 4 0"/><path d="M3 3l18 18"/></svg>
);
export const PhoneIcon = (p: P) => (
  <svg {...glyph(p)}><rect x="6" y="2.5" width="12" height="19" rx="2.5"/><path d="M10.5 18.5h3"/></svg>
);
export const RefreshIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M20 11a8 8 0 1 0-2.3 5.7"/><path d="M20 4v7h-7"/></svg>
);
export const InfoIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="9"/><path d="M12 11v5.5"/><path d="M12 7.8h.01"/></svg>
);
export const HelpIcon = (p: P) => (
  <svg {...glyph(p)}><circle cx="12" cy="12" r="9"/><path d="M9.5 9.5a2.5 2.5 0 1 1 3.5 2.3c-.6.3-1 .9-1 1.5v.7"/><path d="M12 17h.01"/></svg>
);
export const WarningIcon = (p: P) => (
  <svg {...glyph(p)}><path d="M12 4l9 16H3z"/><path d="M12 10v4.5"/><path d="M12 17.3h.01"/></svg>
);
